#ifndef INDRAS_PEARLS_RENDERER_PACKET_H
#define INDRAS_PEARLS_RENDERER_PACKET_H

#define LIMIT_SET_REGION_COUNT 4
#define RENDERER_COMPLEX_COMPONENT_COUNT 2

#define RENDERER_PACKET_CIRCLE_CENTER_OFFSET 0
#define RENDERER_PACKET_CIRCLE_RADIUS_SQUARED_OFFSET \
    (RENDERER_PACKET_CIRCLE_CENTER_OFFSET + LIMIT_SET_REGION_COUNT * RENDERER_COMPLEX_COMPONENT_COUNT)
#define RENDERER_PACKET_A_OFFSET \
    (RENDERER_PACKET_CIRCLE_RADIUS_SQUARED_OFFSET + LIMIT_SET_REGION_COUNT)
#define RENDERER_PACKET_B_OFFSET \
    (RENDERER_PACKET_A_OFFSET + LIMIT_SET_REGION_COUNT * RENDERER_COMPLEX_COMPONENT_COUNT)
#define RENDERER_PACKET_C_OFFSET \
    (RENDERER_PACKET_B_OFFSET + LIMIT_SET_REGION_COUNT * RENDERER_COMPLEX_COMPONENT_COUNT)
#define RENDERER_PACKET_D_OFFSET \
    (RENDERER_PACKET_C_OFFSET + LIMIT_SET_REGION_COUNT * RENDERER_COMPLEX_COMPONENT_COUNT)
#define RENDERER_PACKET_FLOAT_COUNT \
    (RENDERER_PACKET_D_OFFSET + LIMIT_SET_REGION_COUNT * RENDERER_COMPLEX_COMPONENT_COUNT)

enum renderer_packet_status {
    RENDERER_PACKET_OK = 0,
    RENDERER_PACKET_INVALID_PARAMETER,
    RENDERER_PACKET_OUTSIDE_CLASSICAL_DOMAIN,
    RENDERER_PACKET_INVALID_PRESENTATION,
    RENDERER_PACKET_NUMERIC_FAILURE
};

/*
 * Compiler-neutral Android boundary: one ordinary float plus one float array.
 * No C aggregate, _Complex value, or compiler-private representation crosses it.
 */
int symmetric_classical_renderer_packet(
    float radius,
    float output[static RENDERER_PACKET_FLOAT_COUNT]
);

#endif
